### ISSUE TITLE
Option to change video size on game details screen

### ISSUE THREAD

**Issue by SirBossJam** [PlayingKarrde/gameOS#170] opened 2021-03-17 14:07 UTC
Video seems to be stretched past the screen boundaries. This doesn't seem optimal. It also affects the lower portion of the video  where it blends to the lower portion of the screen, cutting off the video at the bottom. I'd like to see more of the video and have some options around the sizing or placement of the elements on the game details screen.

I've tried with both 4k & 1080p, with the same result.

**Comment by PlayingKarrde** [comment] 2021-03-17 19:23
Could you provide a screenshot? I'm not sure I understand the issue

**Comment by SirBossJam** [comment] 2021-03-17 23:11
Sure. See attached. There's definitely more that should be showing for the video (status bars, etc.) at the top. It's not just this video though.
![Screenshot_2021-03-17_18-10-23](https://user-images.githubusercontent.com/66538223/111550502-274a3f00-8776-11eb-9044-5d90f45f30e0.png)

**Comment by HVR88** [comment] 2021-04-08 17:30
The video looks like it's been correctly scaled. The video is 4:3 (SNES) and because you're displaying it in 16:9 (fill the screen), you're going to lose the top and bottom. The alternative would require black bars on the sides to preserve the 4:3 aspect.

**Comment by HVR88** [comment] 2021-04-08 17:34
4:3 Original

![image](https://user-images.githubusercontent.com/33399216/114071303-f76ef280-986e-11eb-9a3c-c4afe5d1b82d.png)

Cropped to fill 16:9 display (approximated):

![image](https://user-images.githubusercontent.com/33399216/114071419-153c5780-986f-11eb-9596-16419fc49807.png)

**Comment by PlayingKarrde** [comment] 2021-07-30 18:41
I'm going to close this as, as @HVR88 states, it is as designed

**Closed by PlayingKarrde** 2021-07-30 18:41 UTC
